app = "testDirIp"

[build]
  # No especificamos dockerfile, usará python-build estándar

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

[python]
compile = true
